version: '2'

services:
  frontend-apps:
    container_name: vulnerability-assessment-tool-frontend-apps
    hostname: frontend-apps
    build: 
      context: ./frontend-apps
      dockerfile: ./Dockerfile
      args:
        - VULAS_RELEASE=${VULAS_RELEASE}
    image: vulnerability-assessment-tool-frontend-apps:${VULAS_RELEASE}
    expose:
      - "8080"
    security_opt:
      - no-new-privileges

  frontend-bugs:
    container_name: vulnerability-assessment-tool-frontend-bugs
    hostname: frontend-bugs
    build: 
      context: ./frontend-bugs
      dockerfile: ./Dockerfile
      args:
        - VULAS_RELEASE=${VULAS_RELEASE}
    image: vulnerability-assessment-tool-frontend-bugs:${VULAS_RELEASE}
    expose:
      - "8080"
    security_opt:
      - no-new-privileges

  haproxy:
    container_name: vulnerability-assessment-tool-haproxy
    hostname: haproxy
    env_file: .env
    build: 
      context: ./haproxy
      dockerfile: ./Dockerfile
      args:
        - VULAS_RELEASE=${VULAS_RELEASE}
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
    image: vulnerability-assessment-tool-haproxy:${VULAS_RELEASE}
    restart: unless-stopped
    ports:
      - "8033:8080"
      - "8034:7070"
    volumes:
      - "./haproxy/conf/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
    depends_on:
      - frontend-apps
      - frontend-bugs
      - rest-backend
      - rest-lib-utils
    security_opt:
      - no-new-privileges

  patch-lib-analyzer:
    container_name: vulnerability-assessment-tool-patch-lib-analyzer
    hostname: patch-lib-analyzer
    build: 
      context: ./patch-lib-analyzer
      dockerfile: ./Dockerfile
      args:
        - VULAS_RELEASE=${VULAS_RELEASE}
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
    image: vulnerability-assessment-tool-patch-lib-analyzer:${VULAS_RELEASE}
    expose:
      - "8080"
    volumes:
      - "./data/patcheval:/patcheval-data"
    links:
      - rest-backend:backend
      - rest-lib-utils:cia
    depends_on: 
      - rest-backend
    environment:
      - PATCHEVAL_OPTS=-bug "" -folder /patcheval-data -j -h 0 -p 6
      - vulas.shared.cia.serviceUrl=http://cia:8092/cia
      - vulas.shared.backend.serviceUrl=http://backend:8091/backend
      - vulas.patchEval.onlyAddNewResults=true
    security_opt:
      - no-new-privileges
  
  postgresql:
    container_name: vulnerability-assessment-tool-postgresql
    hostname: postgresql
    build: 
      context: ./postgresql
      dockerfile: ./Dockerfile
      args:
        - VULAS_RELEASE=${VULAS_RELEASE}
    image: vulnerability-assessment-tool-postgresql:${VULAS_RELEASE}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "8032:5432"
    volumes:
      - vulnerability-assessment-tool-postgres-data:/var/lib/postgresql/data
    security_opt:
      - no-new-privileges

  rest-backend:
    container_name: vulnerability-assessment-tool-rest-backend
    hostname: rest-backend
    env_file: 
      - .env
      - ./rest-backend/conf/restbackend.properties
    build: 
      context: ./rest-backend    
      dockerfile: ./Dockerfile
      args:
        - VULAS_RELEASE=${VULAS_RELEASE}
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
    image: vulnerability-assessment-tool-rest-backend:${VULAS_RELEASE}
    expose:
      - "8091"
    environment:
      - DELAY_STARTUP=5
      - vulas.shared.cia.serviceUrl=http://cia:8092/cia
      - vulas.backend.coverageService.langConfidenceThreshold=0.2
      - vulas.backend.coverageService.licenseConfidenceThreshold=0.2
      - spring.datasource.username=${POSTGRES_USER}
      - spring.datasource.password=${POSTGRES_PASSWORD}
    links:
      - postgresql:postgresql
      - rest-lib-utils:cia
    volumes:
      - "./data/db-dump/flyway-callbacks:/flyway-callbacks"
    depends_on: 
      - postgresql
    security_opt:
      - no-new-privileges

  rest-lib-utils:
    container_name: vulnerability-assessment-tool-rest-lib-utils
    hostname: rest-lib-utils
    build: 
      context: ./rest-lib-utils 
      dockerfile: ./Dockerfile
      args:
        - VULAS_RELEASE=${VULAS_RELEASE}
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
    image: vulnerability-assessment-tool-rest-lib-utils:${VULAS_RELEASE}
    expose:
        - "8092"
    volumes:
      - "./data/rest-lib-utils:/root/"
    security_opt:
      - no-new-privileges
  
volumes:
  vulnerability-assessment-tool-postgres-data:
